/**
 * The step between the code a player types and the room handle the realtime
 * framework understands.
 *
 * Two identifiers exist per room and they are not interchangeable:
 *
 * - `Room.code` — six characters from the unambiguous alphabet, ours, global
 *   across games, the only one a player ever sees or types. It is a
 *   **capability, not an identifier** (ADR-0001 §6): holding it is what
 *   authorises a join. That is why no room is ever enumerable.
 * - `Room.realtimeRoomId` — the realtime framework's own opaque handle,
 *   generated by the framework when it creates the room that backs this one
 *   (ADR-0001 §4.1 rev 4). Internal plumbing. It is *also* a join capability,
 *   because joining by id needs nothing else, so it travels only to a client
 *   the join matrix has already admitted — and never to a game module, which
 *   sees neither identifier.
 *
 * The mapping rides on the room record itself rather than on a second key, so
 * it inherits the room's TTL and cannot outlive it. A mapping with its own
 * lifecycle would be a join capability that leaks after the room is gone.
 *
 * Nothing in this file names the framework. `platform-core` hosts the lobby
 * above the `RoomRunner` seam and must not learn what is underneath it
 * (ADR-0001 §4.1) — the handle is an opaque string here and stays one.
 */

import { type Room, type RoomStatus, isRoomMember, seatIndexOf } from './types.js'

/**
 * Whether a room still needs a realtime binding, or has aged past the point of
 * deserving one. A closed room must never be bound: the framework room behind
 * it is gone, and binding would hand out a handle that resolves to nothing.
 */
const BINDABLE_STATUSES: readonly RoomStatus[] = ['lobby', 'in_progress', 'finished']

export type RealtimeBindingDecision =
  /** Not bound yet — write `realtimeRoomId`. */
  | { readonly action: 'bind' }
  /** Already bound to this exact handle. An idempotent replay; write nothing. */
  | { readonly action: 'noop' }
  /** Bound to a different handle, or not bindable at all. */
  | {
      readonly action: 'reject'
      readonly code: 'already_bound' | 'room_closed' | 'invalid_handle'
    }

/**
 * Pure binding rule, separated from the store so every branch is testable
 * without one.
 *
 * Rebinding a live room to a *different* handle is refused rather than
 * overwritten. Two framework rooms claiming the same platform room is how a
 * lobby silently splits in half — half the players in one, half in the other,
 * each seeing a room that looks correct. The realtime service must close its
 * duplicate and re-read, not win the race.
 */
export function decideRealtimeBinding(room: Room, realtimeRoomId: string): RealtimeBindingDecision {
  if (realtimeRoomId.trim().length === 0) return { action: 'reject', code: 'invalid_handle' }
  if (!BINDABLE_STATUSES.includes(room.status)) return { action: 'reject', code: 'room_closed' }
  if (room.realtimeRoomId === null) return { action: 'bind' }
  if (room.realtimeRoomId === realtimeRoomId) return { action: 'noop' }
  return { action: 'reject', code: 'already_bound' }
}

export type BindRealtimeRoomFailure =
  | { readonly code: 'room_not_found' }
  | { readonly code: 'room_closed' }
  | { readonly code: 'invalid_handle' }
  | { readonly code: 'already_bound'; readonly realtimeRoomId: string }
  /**
   * The room exists and the binding is legal, but the compare-and-set retry
   * budget ran out. Distinct from `room_not_found` on purpose: the caller
   * should retry, and reporting a missing room would send it to create a
   * second framework room for a room that is very much alive.
   */
  | { readonly code: 'contended'; readonly retryAfterMs: number }

export type BindRealtimeRoomResult =
  | {
      readonly ok: true
      readonly room: Room
      /** False when the room was already bound to this handle (replay). */
      readonly bound: boolean
    }
  | { readonly ok: false; readonly error: BindRealtimeRoomFailure }

export type RealtimeJoinTarget =
  | {
      readonly ok: true
      readonly roomId: string
      readonly realtimeRoomId: string
      /** Null for a spectator. */
      readonly seatIndex: number | null
    }
  | { readonly ok: false; readonly code: 'not_bound' | 'not_admitted' }

/**
 * What a client needs to enter the realtime room, and the only sanctioned way
 * to obtain it.
 *
 * Two guards, in this order:
 *
 * 1. `not_admitted` — the player is neither seated nor spectating in this room,
 *    so the join matrix has not admitted them and the handle is not theirs. A
 *    caller that skipped `joinByCode` and reached straight for the handle is
 *    exactly the bug this catches.
 * 2. `not_bound` — the realtime service has not created the backing room yet.
 *    The client waits and retries; it is never told to guess a handle.
 */
export function realtimeJoinTarget(room: Room, playerId: string): RealtimeJoinTarget {
  if (!isRoomMember(room, playerId)) return { ok: false, code: 'not_admitted' }
  if (room.realtimeRoomId === null) return { ok: false, code: 'not_bound' }
  return {
    ok: true,
    roomId: room.id,
    realtimeRoomId: room.realtimeRoomId,
    seatIndex: seatIndexOf(room, playerId),
  }
}

/**
 * What a *listing* may show. Every field here is deliberate, and so is every
 * absence: no `code`, no `realtimeRoomId`, no player ids.
 *
 * The framework's own matchmaker room listing stays off (ADR-0001 §6) — a
 * listable lobby hands a join capability to anyone who asks the server for the
 * list. Our flag-gated listing has to hold the same line, so it is typed to
 * make the leak unrepresentable rather than merely absent today.
 */
export interface PublicRoomSummary {
  readonly id: string
  readonly gameId: string
  readonly gameSlug: string
  readonly gameVersion: string
  readonly status: RoomStatus
  readonly seatsTotal: number
  readonly seatsTaken: number
  readonly spectatorCount: number
  readonly createdAt: number
}

export function publicRoomSummary(room: Room): PublicRoomSummary {
  return {
    id: room.id,
    gameId: room.gameId,
    gameSlug: room.gameSlug,
    gameVersion: room.gameVersion,
    status: room.status,
    seatsTotal: room.seats.length,
    seatsTaken: room.seats.filter((seat) => seat.occupantPlayerId !== null).length,
    spectatorCount: room.spectatorPlayerIds.length,
    createdAt: room.createdAt,
  }
}
