/**
 * The route table.
 *
 * Both the web shell and the realtime service build and parse these URLs, and
 * a share link that works in WhatsApp but not in Discord is a product bug. So
 * the shapes live here, once, as builders and a parser — nobody concatenates
 * a path by hand.
 *
 * `/r/:CODE` is deliberately a *universal* room link: it carries no game slug,
 * so the code alone resolves its own game. That is what lets someone paste a
 * code into a chat without explaining what it is for, and what keeps the link
 * valid if a room is ever migrated between games.
 */

import { canonicalizeRoomCode } from '../rooms/join.js'

export const ROUTE_PATTERNS = {
  home: '/',
  games: '/games',
  game: '/play/:slug',
  newRoom: '/play/:slug/new',
  room: '/r/:code',
  match: '/match/:id',
  /** Friendly landing for an unknown, expired or malformed code. */
  roomNotFound: '/r/not-found',
} as const

export const routes = {
  home: (): string => '/',
  games: (): string => '/games',
  game: (slug: string): string => `/play/${encodeURIComponent(slug)}`,
  newRoom: (slug: string): string => `/play/${encodeURIComponent(slug)}/new`,
  /** Always emits the canonical upper-case code. */
  room: (code: string): string => `/r/${code.toUpperCase()}`,
  match: (matchId: string): string => `/match/${encodeURIComponent(matchId)}`,
  roomNotFound: (reason?: string): string =>
    reason === undefined ? '/r/not-found' : `/r/not-found?reason=${encodeURIComponent(reason)}`,
} as const

/** Absolute URL for a share link or an `og:url`. `origin` has no trailing slash. */
export function absoluteUrl(origin: string, path: string): string {
  return `${origin.replace(/\/+$/, '')}${path}`
}

export type ParsedRoute =
  | { readonly name: 'home' }
  | { readonly name: 'games' }
  | { readonly name: 'game'; readonly slug: string }
  | { readonly name: 'newRoom'; readonly slug: string }
  /**
   * `code` is canonical. `redirectTo` is set when the URL as typed was not —
   * `/r/abc-123` resolves, and the handler should 308 to `/r/ABC123` so the
   * canonical form is what gets shared onward and what link previews cache.
   */
  | { readonly name: 'room'; readonly code: string; readonly redirectTo: string | null }
  | { readonly name: 'roomNotFound' }
  | { readonly name: 'match'; readonly matchId: string }
  | { readonly name: 'unknown' }

const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/

/**
 * Parses a pathname (no query, no origin) into a route.
 *
 * Tolerant in exactly the ways a shared link needs: a trailing slash, mixed
 * case in a room code, and the separators a phone keyboard or a chat app adds
 * around a code. Not tolerant about slugs — a slug is generated by us, so a
 * malformed one is a bad link, not a typo.
 */
export function parseRoute(pathname: string): ParsedRoute {
  const path = pathname.split('?')[0]!.split('#')[0]!
  const segments = path
    .split('/')
    .filter((segment) => segment.length > 0)
    .map(decodeURIComponent)

  if (segments.length === 0) return { name: 'home' }

  const [first, second, third] = segments

  if (first === 'games' && segments.length === 1) return { name: 'games' }

  if (first === 'play' && second !== undefined) {
    if (!SLUG_PATTERN.test(second)) return { name: 'unknown' }
    if (segments.length === 2) return { name: 'game', slug: second }
    if (segments.length === 3 && third === 'new') return { name: 'newRoom', slug: second }
    return { name: 'unknown' }
  }

  if (first === 'r' && second !== undefined && segments.length === 2) {
    if (second === 'not-found') return { name: 'roomNotFound' }
    const code = canonicalizeRoomCode(second)
    if (code === null) return { name: 'roomNotFound' }
    const canonicalPath = routes.room(code)
    return { name: 'room', code, redirectTo: path === canonicalPath ? null : canonicalPath }
  }

  if (first === 'match' && second !== undefined && segments.length === 2) {
    return { name: 'match', matchId: second }
  }

  return { name: 'unknown' }
}
